"""Installing a certificate the customer already has — Ploi's "install existing certificate".

Every certificate here is a REAL one, generated by `cryptography` in the test. A hand-written
PEM fixture proves that our parser accepts the fixture; only a real key pair proves that the
match check would catch a mismatched one.

The two refusals that matter both happen before the server is touched, and both are things
that look fine on screen and break the machine:

* a key that does not belong to the certificate makes nginx **refuse to start**, which on a
  shared server takes down every site on it — not only this one;
* a certificate for the wrong domain gives every visitor a name warning, which is worse than
  no HTTPS because the padlock says it was handled.
"""
import datetime as dt

import pytest
from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

from app.services import cert_install_service as ci


def make_cert(common="shop.com", sans=("shop.com",), days=90, start_days=-1, ca=False,
              issuer_name=None, key=None):
    """A real certificate and its real key."""
    key = key or rsa.generate_private_key(public_exponent=65537, key_size=2048)
    subject = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, common)])
    issuer = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, issuer_name or common)])
    now = dt.datetime.now(dt.timezone.utc)
    builder = (
        x509.CertificateBuilder()
        .subject_name(subject).issuer_name(issuer)
        .public_key(key.public_key()).serial_number(x509.random_serial_number())
        .not_valid_before(now + dt.timedelta(days=start_days))
        .not_valid_after(now + dt.timedelta(days=days))
    )
    if sans:
        builder = builder.add_extension(
            x509.SubjectAlternativeName([x509.DNSName(n) for n in sans]), critical=False)
    if ca:
        builder = builder.add_extension(x509.BasicConstraints(ca=True, path_length=None),
                                        critical=True)
    cert = builder.sign(key, hashes.SHA256())
    return (cert.public_bytes(serialization.Encoding.PEM).decode(),
            key.private_bytes(serialization.Encoding.PEM,
                              serialization.PrivateFormat.PKCS8,
                              serialization.NoEncryption()).decode(),
            key)


# ── The two refusals that protect the machine ────────────────────────────────

def test_a_key_from_a_different_certificate_is_refused():
    """The one that takes the whole web server down. nginx will not start with a mismatched
    pair, so on a shared box every OTHER site goes with it."""
    cert, _key, _k = make_cert()
    _c2, other_key, _k2 = make_cert()
    with pytest.raises(ci.CertError) as exc:
        ci.check(cert, other_key, "shop.com")
    assert "does not belong" in str(exc.value)


def test_the_matching_pair_is_accepted():
    cert, key, _k = make_cert()
    out = ci.check(cert, key, "shop.com")
    assert out["names"] == ["shop.com"]
    assert out["days_left"] > 80


def test_a_certificate_for_another_domain_is_refused():
    """Installing it would show a warning to every visitor — worse than no HTTPS, because
    it looks handled."""
    cert, key, _k = make_cert(common="other.com", sans=("other.com",))
    with pytest.raises(ci.CertError) as exc:
        ci.check(cert, key, "shop.com")
    assert "other.com" in str(exc.value) and "shop.com" in str(exc.value)


# ── Wildcards, exactly as a browser reads them ───────────────────────────────

@pytest.mark.parametrize("names,domain,expected", [
    (["*.shop.com"], "www.shop.com", True),
    (["*.shop.com"], "shop.com", False),          # a wildcard does NOT cover the bare name
    (["*.shop.com"], "a.b.shop.com", False),      # …nor two labels deep
    (["shop.com", "*.shop.com"], "shop.com", True),
    (["*.shop.com"], "www.shop.com.evil.com", False),
    (["shop.com"], "SHOP.COM", True),             # case is not part of a hostname
    ([], "shop.com", False),
])
def test_wildcard_matching_is_no_more_generous_than_a_browser(names, domain, expected):
    """Being generous here means installing a certificate browsers then reject — the failure
    lands on the visitor, not on us."""
    assert ci.covers(names, domain) is expected


def test_a_wildcard_certificate_installs_on_a_subdomain():
    cert, key, _k = make_cert(common="*.shop.com", sans=("*.shop.com",))
    assert ci.check(cert, key, "www.shop.com")["names"] == ["*.shop.com"]


# ── Dates ────────────────────────────────────────────────────────────────────

def test_an_expired_certificate_is_refused():
    """Strictly worse than none: the browser refuses the page outright instead of marking
    it insecure."""
    cert, key, _k = make_cert(days=-1, start_days=-30)
    with pytest.raises(ci.CertError) as exc:
        ci.check(cert, key, "shop.com")
    assert "expired" in str(exc.value)


def test_a_certificate_that_is_not_valid_yet_is_refused():
    cert, key, _k = make_cert(days=90, start_days=5)
    with pytest.raises(ci.CertError) as exc:
        ci.check(cert, key, "shop.com")
    assert "not valid until" in str(exc.value)


# ── What people actually paste ───────────────────────────────────────────────

def test_the_certificate_pasted_into_the_key_box_is_named_precisely():
    """The single most likely mistake. "Could not be read" would send somebody looking at
    the wrong file."""
    cert, _key, _k = make_cert()
    with pytest.raises(ci.CertError) as exc:
        ci.check(cert, cert, "shop.com")
    assert "not a private key" in str(exc.value)


def test_a_passphrase_protected_key_is_refused_with_the_way_out():
    """nginx cannot be asked for a passphrase when it starts, so the server simply never
    comes up — a failure with no visible cause."""
    _c, _k, key = make_cert()
    locked = key.private_bytes(
        serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
        serialization.BestAvailableEncryption(b"secret")).decode()
    cert, _plain, _kk = make_cert(key=key)
    with pytest.raises(ci.CertError) as exc:
        ci.check(cert, locked, "shop.com")
    assert "passphrase" in str(exc.value) and "openssl" in str(exc.value)


def test_rubbish_is_refused_before_anything_happens():
    with pytest.raises(ci.CertError):
        ci.check("hello", "world", "shop.com")


def test_a_chain_pasted_in_the_wrong_order_is_put_right():
    """Leaf-then-intermediate is what nginx wants. The other way round produces a
    certificate some devices accept and others reject — the worst kind to diagnose."""
    ca_pem, _ca_key, _k = make_cert(common="Test CA", sans=(), ca=True)
    leaf_pem, _key, _k2 = make_cert(issuer_name="Test CA")
    fixed = ci.normalise_chain(ca_pem + leaf_pem)
    assert fixed.count("BEGIN CERTIFICATE") == 2, "nothing may be dropped"
    first = x509.load_pem_x509_certificate(
        (fixed.split("-----END CERTIFICATE-----")[0] + "-----END CERTIFICATE-----\n").encode())
    assert first.subject.rfc4514_string() == "CN=shop.com", "the leaf must come first"


def test_a_self_signed_certificate_is_reported_not_refused():
    """A Cloudflare origin certificate is self-signed as far as a public root store is
    concerned, and it is a perfectly good thing to install."""
    cert, key, _k = make_cert()
    assert ci.check(cert, key, "shop.com")["self_signed"] is True


# ── Paths ────────────────────────────────────────────────────────────────────

def test_the_paths_come_from_the_domain_and_nothing_else():
    p = ci.paths_for("shop.com")
    assert p["cert"] == "/etc/ssl/serverally/shop.com/fullchain.pem"
    assert p["key"] == "/etc/ssl/serverally/shop.com/privkey.pem"


@pytest.mark.parametrize("bad", ["../../etc", "a b.com", "shop.com/../..", "$(id).com"])
def test_a_domain_that_is_not_a_hostname_never_becomes_a_path(bad):
    """A path built from caller text is a path that can point at /etc/shadow."""
    from app.services import ssl_service

    with pytest.raises(ssl_service.SslError):
        ci.paths_for(bad)


# ── The command ──────────────────────────────────────────────────────────────

def test_nothing_secret_is_ever_an_argument():
    """The reason the key travels by SFTP. A command's arguments are visible in `ps` while it
    runs and are kept in the stored output of the run."""
    _c, key, _k = make_cert()
    cmd = ci.build_install_command("/etc/nginx/x.conf", "shop.com")
    assert "PRIVATE KEY" not in cmd
    assert key.splitlines()[1] not in cmd


def test_the_key_is_written_readable_by_root_only():
    cmd = ci.build_install_command("/etc/nginx/x.conf", "shop.com")
    assert "chmod 600 /etc/ssl/serverally/shop.com/privkey.pem" in cmd


def test_the_configuration_is_backed_up_and_restored():
    cmd = ci.build_install_command("/etc/nginx/x.conf", "shop.com")
    assert 'cp -p "$CFG" "$BAK"' in cmd
    assert "restore" in cmd


def test_the_web_server_must_accept_the_config_before_anything_is_reloaded():
    """A configuration that does not parse does not break one site — the reload fails for
    the whole machine."""
    cmd = ci.build_install_command("/etc/nginx/x.conf", "shop.com")
    assert cmd.index("nginx -t") < cmd.index("reload nginx")


def test_apache_gets_apache_directives():
    cmd = ci.build_install_command("/etc/apache2/x.conf", "shop.com", apache=True)
    assert "apachectl configtest" in cmd
    assert "SSLCertificateFile" in cmd


def test_success_is_judged_on_content_not_a_status_code():
    """A site can answer 200 with a blank body. A certificate "installed" onto a page that
    serves nothing is not a success."""
    cmd = ci.build_install_command("/etc/nginx/x.conf", "shop.com")
    assert 'BODY=$(curl' in cmd and '[ -z "$BODY" ]' in cmd


def test_a_site_that_was_already_broken_keeps_the_certificate():
    """Found in the WordPress switches and it applies here too: rolling back on a
    pre-existing outage leaves somebody unable to install a certificate at exactly the moment
    they are fixing the site."""
    cmd = ci.build_install_command("/etc/nginx/x.conf", "shop.com")
    assert "WAS=$(curl" in cmd
    assert cmd.index("WAS=$(curl") < cmd.index('cp -p "$CFG" "$BAK"'), (
        "the before-state has to be read BEFORE the change")
    assert "OK-BROKEN" in cmd


# ── What the customer reads ──────────────────────────────────────────────────

@pytest.mark.parametrize("code,out,ok,says", [
    (0, ">>> OK: 200", True, "installed"),
    (0, ">>> OK-BROKEN: 500", True, "already not"),
    (1, ">>> ERROR: the web server refused the new configuration", False, "refused"),
    (1, ">>> ERROR: the site stopped serving after the change", False, "put back"),
    (1, "no listener to add HTTPS to", False, "hand-written"),
    (1, "some unrelated noise", False, "nothing was changed"),
])
def test_the_message_is_ours_and_never_the_script_s_last_line(code, out, ok, says):
    got_ok, message = ci.explain(code, out)
    assert got_ok is ok
    assert says in message


# ── Run it, do not read it ───────────────────────────────────────────────────
#
# Everything below EXECUTES the generated script with the web server and curl replaced by
# stubs. The first test here exists because the first version of this module had a bug that
# reading it did not reveal: the insertion matched both `listen 80;` and `listen [::]:80;`,
# so nginx got a duplicate listener and refused to start — for every site on the machine.

import subprocess


NGINX_PLAIN = """\
server {
    listen 80;
    listen [::]:80;
    server_name shop.com;
    root /var/www/shop;
}
"""

NGINX_HTTPS = """\
server {
    listen 80;
    server_name shop.com;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name shop.com;
    ssl_certificate     /etc/letsencrypt/live/shop.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shop.com/privkey.pem;
    root /var/www/shop;
}
"""


def run_script(tmp_path, config: str, *, accepts=True, code="200", body="THE REAL SHOP",
               before="200"):
    """Run the real generated command with stubbed nginx/systemctl/curl."""
    binstub = tmp_path / "bin"
    binstub.mkdir(exist_ok=True)
    (binstub / "nginx").write_text(
        "#!/bin/sh\n" + ("exit 0\n" if accepts else "echo 'nginx: [emerg] bad' >&2; exit 1\n"))
    (binstub / "systemctl").write_text("#!/bin/sh\nexit 0\n")
    # Two curl shapes are used: one asks for the body, one asks only for the status code.
    # `WAS` (the before-state) is read first, so the stub answers that one differently.
    (binstub / "curl").write_text(
        "#!/bin/sh\n"
        'if [ -f /tmp/sa_seen ]; then C="' + code + '"; else C="' + before + '"; touch /tmp/sa_seen; fi\n'
        'case "$*" in\n'
        '  *-w*) printf "%s" "$C" ;;\n'
        '  *) printf "%s" "' + body + '" ;;\n'
        "esac\n")
    for f in ("nginx", "systemctl", "curl"):
        (binstub / f).chmod(0o755)

    cfg = tmp_path / "shop.conf"
    cfg.write_text(config)
    ssl_dir = tmp_path / "ssl"
    ssl_dir.mkdir(exist_ok=True)

    cmd = ci.build_install_command(str(cfg), "shop.com")
    # Point the real paths at the temporary directory, and create the incoming files the way
    # SFTP would have.
    cmd = cmd.replace("/etc/ssl/serverally/shop.com", str(ssl_dir))
    (ssl_dir / "fullchain.pem.new").write_text("NEW-CERT\n")
    (ssl_dir / "privkey.pem.new").write_text("NEW-KEY\n")

    proc = subprocess.run(
        ["bash", "-c", f'rm -f /tmp/sa_seen; export PATH="{binstub}:$PATH"; {cmd}'],
        capture_output=True, text=True)
    return proc.returncode, cfg.read_text(), proc.stdout + proc.stderr, ssl_dir


def test_https_is_added_once_per_block_not_once_per_listen_line(tmp_path):
    """The bug that only running it revealed. An ordinary vhost has BOTH `listen 80;` and
    `listen [::]:80;`; inserting after each gives nginx a duplicate 443 listener, and nginx
    then refuses to start — taking down every site on the machine, not just this one."""
    code, text, out, _ssl = run_script(tmp_path, NGINX_PLAIN)
    assert code == 0, out
    assert text.count("listen 443 ssl;") == 1, text
    assert text.count("listen [::]:443 ssl;") == 1, text
    assert text.count("ssl_certificate ") == 1


def test_a_site_that_already_has_https_is_repointed_in_every_block(tmp_path):
    """A site whose http and https halves use different certificates is a bug nobody can see
    from one screen — and no new listener may be added, or nginx refuses to start."""
    code, text, out, ssl_dir = run_script(tmp_path, NGINX_HTTPS)
    assert code == 0, out
    assert "letsencrypt" not in text
    assert text.count(f"ssl_certificate {ssl_dir}/fullchain.pem;") == 1
    assert text.count("listen 443 ssl;") == 1, "an existing listener must not be duplicated"


def test_a_refused_configuration_changes_nothing(tmp_path):
    """A configuration that does not parse does not break one site — the reload fails for
    the whole machine, so the file must go back exactly as it was."""
    code, text, out, ssl_dir = run_script(tmp_path, NGINX_PLAIN, accepts=False)
    assert code == 1
    assert text == NGINX_PLAIN, "the configuration must be byte-identical"
    assert "refused the new configuration" in out
    assert not list(ssl_dir.glob("*.prev")), "no leftovers"


def test_a_refused_configuration_puts_the_previous_certificate_back(tmp_path):
    """Replacing a certificate overwrites the live files BEFORE the config is known to be
    good. Without putting them back, a refused change leaves the running site pointing at a
    file we swapped underneath it."""
    ssl_dir = tmp_path / "ssl"
    ssl_dir.mkdir()
    (ssl_dir / "fullchain.pem").write_text("OLD-CERT\n")
    (ssl_dir / "privkey.pem").write_text("OLD-KEY\n")
    code, _text, out, _s = run_script(tmp_path, NGINX_HTTPS, accepts=False)
    assert code == 1, out
    assert (ssl_dir / "fullchain.pem").read_text() == "OLD-CERT\n"
    assert (ssl_dir / "privkey.pem").read_text() == "OLD-KEY\n"


def test_a_blank_page_after_the_change_is_a_failure(tmp_path):
    """200 is not proof. A certificate installed onto a page that serves nothing is not a
    success, and the config goes back."""
    code, text, out, _s = run_script(tmp_path, NGINX_PLAIN, body="")
    assert code == 1
    assert text == NGINX_PLAIN
    assert "stopped serving" in out


def test_a_site_that_was_already_down_keeps_the_certificate(tmp_path):
    """Rolling back on a pre-existing outage would leave somebody unable to install a
    certificate at exactly the moment they are fixing the site."""
    code, text, out, _s = run_script(tmp_path, NGINX_PLAIN, before="500", code="500", body="")
    assert code == 0, out
    assert "OK-BROKEN" in out
    assert "listen 443 ssl;" in text, "the certificate stays in place"


def test_a_configuration_with_no_plain_listener_is_refused_honestly(tmp_path):
    """A hand-written vhost we cannot safely extend gets a message naming the way forward,
    not a silent no-op that looks like success."""
    code, _text, out, _s = run_script(tmp_path, "server {\n    listen 8080;\n}\n")
    assert code == 1
    assert "no listener to add HTTPS to" in out
    assert ci.explain(code, out) == (False, ci.explain(code, out)[1])
    assert "hand-written" in ci.explain(code, out)[1]


def test_the_key_really_ends_up_readable_by_root_only(tmp_path):
    import os
    import stat

    _code, _text, _out, ssl_dir = run_script(tmp_path, NGINX_PLAIN)
    mode = stat.S_IMODE(os.stat(ssl_dir / "privkey.pem").st_mode)
    assert mode == 0o600, oct(mode)
    assert stat.S_IMODE(os.stat(ssl_dir / "fullchain.pem").st_mode) == 0o644


def test_the_directory_is_made_before_the_upload_and_kept_shut(tmp_path):
    """SFTP does not create parent directories, so a site's FIRST certificate would fail to
    upload at all. And 700 rather than 755 both here and in the install: the web server reads
    the key as root before dropping privileges, so nothing else needs to get in."""
    prep = ci.build_prepare_command("shop.com")
    assert "install -d -m 700" in prep
    assert "/etc/ssl/serverally/shop.com" in prep
    assert "-m 755" not in ci.build_install_command("/etc/nginx/x.conf", "shop.com")


def test_the_prepare_command_cannot_be_pointed_anywhere_else():
    from app.services import ssl_service

    with pytest.raises(ssl_service.SslError):
        ci.build_prepare_command("../../root/.ssh")
