/**
 * Reports — a lens over finished missions (Mission Reports, P1). No new backend: a report
 * IS a mission's outcome (its `result` card + transcript), so this reuses the missions
 * endpoints and adds the report-shaped derivations (verdict, Markdown/JSON export, filename).
 * The whole point is one source of truth: Reports, Missions and Log are three views of the
 * same `missions`/`command_logs` data — see docs/MISSION-REPORTS-PLAN.md.
 */
import { redactSecrets } from "@/lib/redactSecrets"
import {
  listMissions,
  getMission,
  type MissionSummary,
  type MissionDetail,
} from "./missions"

/** A mission is "report-worthy" once it has FINISHED (any outcome) — running/awaiting/
 *  interrupted are still in flight, not yet a report. */
const FINISHED = new Set(["complete", "blocked", "failed", "stopped"])

export function isReport(m: MissionSummary): boolean {
  return FINISHED.has(m.status)
}

export async function listReports(serverId?: string): Promise<MissionSummary[]> {
  return (await listMissions(serverId)).filter(isReport)
}

/** Full report = the mission detail (result card + step transcript for the appendix). */
export async function getReport(id: string): Promise<MissionDetail> {
  return getMission(id)
}

export interface Verdict {
  /** short badge label */
  label: string
  /** semantic tone for coloring */
  tone: "good" | "warn" | "bad" | "neutral"
}

/** The outcome badge a report leads with — mirrors the workspace result card's logic. */
export function reportVerdict(m: MissionSummary): Verdict {
  if (m.status === "complete") {
    if (m.verified === false) return { label: "Not confirmed", tone: "warn" }
    return { label: m.verified ? "Verified" : "Done", tone: "good" }
  }
  if (m.status === "blocked") return { label: "Needs your OK", tone: "warn" }
  if (m.status === "stopped") return { label: "Stopped", tone: "neutral" }
  return { label: "Failed", tone: "bad" }
}

/** The site/target the report is about (the website when present, else the server). */
export function reportSubject(m: MissionSummary): string {
  return m.result?.subject || m.server_name || "your server"
}

function slug(s: string): string {
  return s.replace(/[^a-z0-9.-]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "report"
}

/** e.g. serverally-report-desktopit.net-2026-07-14.md */
export function reportFilename(m: MissionSummary, ext: "md" | "json"): string {
  const day = (m.updated_at || m.created_at || "").slice(0, 10) || "report"
  return `serverally-report-${slug(reportSubject(m))}-${day}.${ext}`
}

function bullets(items: string[] | undefined): string {
  if (!items || items.length === 0) return "_None._\n"
  return items.map((i) => `- ${i}`).join("\n") + "\n"
}

/** A shareable Markdown report — result card + a secret-redacted step appendix. */
export function reportToMarkdown(m: MissionDetail): string {
  const v = reportVerdict(m)
  const r = m.result
  const date = (m.updated_at || m.created_at || "").slice(0, 10)
  const lines: string[] = [
    `# ServerAlly — Mission Report`,
    ``,
    `**Site:** ${reportSubject(m)}  `,
    `**Server:** ${m.server_name ?? "—"}  `,
    `**Outcome:** ${v.label}  `,
    `**Date:** ${date || "—"}  `,
    `**Goal:** ${m.goal}`,
    ``,
    `## ${r?.headline || m.summary || "Mission outcome"}`,
    ``,
  ]
  if (r) {
    lines.push(`### Found`, bullets(r.found), `### Ally did`, bullets(r.did), `### Left for you`, bullets(r.left))
  } else if (m.summary) {
    lines.push(m.summary, ``)
  }
  // Redacted technical appendix — the step-by-step, secrets masked.
  const steps = m.steps ?? []
  if (steps.length) {
    lines.push(`---`, ``, `## Technical log (${steps.length} steps)`, ``)
    steps.forEach((s, i) => {
      const desc = redactSecrets(s.description || s.cmd || "").text
      lines.push(`${i + 1}. ${desc}`)
    })
    lines.push(``)
  }
  lines.push(`---`, `_Generated by ServerAlly · Mission ${m.id}_`)
  return lines.join("\n")
}

/** A machine-readable report (result + meta + redacted steps) for records/audit. */
export function reportToJson(m: MissionDetail): unknown {
  return {
    site: reportSubject(m),
    server: m.server_name,
    goal: m.goal,
    outcome: reportVerdict(m).label,
    status: m.status,
    verified: m.verified,
    date: m.updated_at || m.created_at,
    result: m.result,
    summary: m.summary,
    steps: (m.steps ?? []).map((s) => ({
      description: redactSecrets(s.description || "").text,
      command: redactSecrets(s.cmd || "").text,
      exit_code: s.exit_code,
      server: s.server,
    })),
    mission_id: m.id,
    generated_by: "ServerAlly",
  }
}

/** Trigger a client-side file download (no backend round-trip). */
export function downloadText(filename: string, text: string, mime = "text/plain"): void {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}
