"""Who ServerAlly is on AWS, and how it becomes a client without holding their key.

**AWS partners are not given an IAM user in a client's account.** They are given a role they
assume, with an external ID. Handing over an access key is the thing a competent client's
security review refuses, and it is also the thing we least want to hold: a key in fifty client
accounts is fifty secrets that can leak, rotate, or outlive the engagement. A role is granted
and revoked by the client, in their own console, and every command we run appears in *their*
CloudTrail.

So an AWS account can be connected two ways:

| Kind | What we store | Who can revoke it |
|---|---|---|
| access key  | the key, encrypted        | us, by deleting it |
| **role**    | an ARN and an external ID | **the client, by detaching a role** |

**The external ID is the whole security of the second one, and it is generated here.**

A role that trusts our AWS account is, without one, open to the confused-deputy problem:
anyone else who is also our customer could give us that role's ARN and ask us to assume it,
and AWS would say yes — because AWS only checks that the *caller* is us. The external ID is
the secret that ties one role to one connection. It therefore must be:

- **generated by us**, never accepted from whoever is connecting — a customer-chosen value can
  be guessed, reused, or deliberately set to another customer's;
- **different for every customer**, so one customer can never satisfy another's trust policy.
  Not per ROLE, and `external_id_for` explains why that is a decision rather than a shortcut.

**Assumed credentials are never stored.** We keep the ARN and the external ID; the actual keys
come from `AssumeRole` per use and live in memory until they expire. There is no row, no file
and no log line containing them.
"""
from __future__ import annotations

import base64
import hmac
import logging
import time

from app.config import settings

logger = logging.getLogger(__name__)

#: How long a session we ask AWS for. An hour is the default maximum a role allows unless the
#: client raised it, and asking for more than the role permits is refused outright.
SESSION_SECONDS = 3600

#: Stop using a cached credential this long before it actually expires, so a command that
#: starts just under the wire does not have it die mid-flight.
_EXPIRY_MARGIN = 300

#: Assumed credentials, in memory only, keyed by role + external id. Never written anywhere.
_assumed: dict[str, tuple[dict, float]] = {}


def base_configured() -> bool:
    """Whether this deployment has an AWS identity for client roles to trust.

    Without one the role option is **absent rather than broken** — the same rule the asset and
    site menus follow. A button that collects an ARN and then cannot use it wastes the
    customer's time and, worse, teaches them the feature does not work.
    """
    return bool(getattr(settings, "AWS_BASE_ACCESS_KEY_ID", "")
                and getattr(settings, "AWS_BASE_SECRET_ACCESS_KEY", ""))


def external_id_for(user_id) -> str:
    """The external ID for this customer, derived rather than stored.

    It has to survive between two moments: we hand it over so the client can put it in their
    role's trust policy, and we use it later when the role is connected. A random value would
    need somewhere to live in between — a table, or a cache with an expiry that is wrong
    either way (too short and a customer who takes a day to get IAM approval comes back to a
    dead value; too long and it is a stored secret with no owner).

    So it is an HMAC of the account id under the deployment's secret key: stable for as long
    as they need, reproducible with nothing written down, and unguessable without the key.

    **It is per CUSTOMER, not per role**, and that is deliberate rather than a shortcut — the
    role ARN does not exist yet at the moment we have to hand the value over. Per customer is
    enough for what the external ID is actually for: the confused-deputy problem is another of
    OUR customers naming a role ARN that is not theirs, and their derived value simply does
    not match, so AWS refuses. Two roles belonging to the same customer sharing one value
    gives that customer nothing they did not already have.
    """
    mac = hmac.new(settings.SECRET_KEY.encode(), f"aws-role:{user_id}".encode(), "sha256")
    return f"serverally-{base64.urlsafe_b64encode(mac.digest()[:18]).decode().rstrip('=')}"


def trust_policy(external_id: str, our_account_id: str) -> dict:
    """The trust policy the client pastes onto the role they create for us.

    Handed over rather than described, because a trust policy typed from a description is a
    trust policy with a typo in it — and the failure mode of a typo'd external ID is an
    AccessDenied nobody can read.
    """
    return {
        "Version": "2012-10-17",
        "Statement": [{
            "Effect": "Allow",
            "Principal": {"AWS": f"arn:aws:iam::{our_account_id}:root"},
            "Action": "sts:AssumeRole",
            "Condition": {"StringEquals": {"sts:ExternalId": external_id}},
        }],
    }


def _base_session(region: str):
    import boto3

    return boto3.session.Session(
        aws_access_key_id=settings.AWS_BASE_ACCESS_KEY_ID,
        aws_secret_access_key=settings.AWS_BASE_SECRET_ACCESS_KEY,
        region_name=region or "us-east-1",
    )


def our_account_id() -> str | None:
    """The AWS account number a client's role must trust. None when we have no identity."""
    if not base_configured():
        return None
    try:
        return _base_session("us-east-1").client("sts").get_caller_identity().get("Account")
    except Exception as exc:  # noqa: BLE001
        logger.warning("Could not read our own AWS account id: %s", exc)
        return None


def is_role(cred: dict) -> bool:
    """Whether this connection is a role rather than a key."""
    return bool((cred or {}).get("role_arn"))


def session_for(cred: dict):
    """A boto3 session for this connected account, whichever kind it is.

    **One place**, because `cloud_service` and `ssm_service` both need it and a second copy is
    how one of them ends up not knowing about roles at all — the exact seam that cost ten
    steps on a live deploy earlier today.
    """
    import boto3

    region = (cred.get("region") or "").strip() or "us-east-1"
    if not is_role(cred):
        return boto3.session.Session(
            aws_access_key_id=cred.get("access_key_id"),
            aws_secret_access_key=cred.get("secret_access_key"),
            region_name=region,
        )

    creds = assume(cred["role_arn"], cred.get("external_id") or "", region)
    return boto3.session.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
        region_name=region,
    )


def assume(role_arn: str, external_id: str, region: str = "us-east-1") -> dict:
    """Short-lived credentials for a client's role.

    Cached in memory for as long as they are valid — a mission running twenty commands should
    not make twenty extra STS calls — and never anywhere else.
    """
    if not base_configured():
        raise AwsRoleError(
            "This ServerAlly deployment has no AWS identity of its own, so it cannot assume a "
            "role in your account. Connect the account with an access key instead, or ask "
            "your administrator to configure one.")
    if not external_id:
        # Refused rather than sent empty: assuming without one is precisely the
        # confused-deputy hole the external ID exists to close.
        raise AwsRoleError(
            "This connection has no external ID, so the role cannot be assumed safely. "
            "Reconnect the account to generate one.")

    key = f"{role_arn}|{external_id}"
    cached = _assumed.get(key)
    if cached and cached[1] - _EXPIRY_MARGIN > time.time():
        return cached[0]

    try:
        out = _base_session(region).client("sts").assume_role(
            RoleArn=role_arn,
            RoleSessionName="serverally",
            ExternalId=external_id,
            DurationSeconds=SESSION_SECONDS,
        )
    except Exception as exc:  # noqa: BLE001
        raise AwsRoleError(_role_message(exc))

    creds = out.get("Credentials") or {}
    if not creds.get("AccessKeyId"):
        raise AwsRoleError("AWS accepted the request but returned no credentials for that role.")
    _assumed[key] = (creds, time.time() + SESSION_SECONDS)
    return creds


def forget(role_arn: str, external_id: str) -> None:
    """Drop cached credentials — used when a connection is removed, so nothing outlives it."""
    _assumed.pop(f"{role_arn}|{external_id}", None)


class AwsRoleError(Exception):
    """Something the customer can read and act on."""


def _role_message(exc: Exception) -> str:
    """AWS says AccessDenied for four quite different mistakes; each has a different fix."""
    text = str(exc)
    if "not authorized to perform: sts:AssumeRole" in text or "AccessDenied" in text:
        return ("AWS refused to let us assume that role. Usually one of three things: the "
                "role's trust policy names a different account, its external ID does not "
                "match the one we generated for this connection, or the role does not exist "
                "in that account. Copy the trust policy from this page onto the role exactly "
                "as it is shown.")
    if "InvalidClientTokenId" in text or "SignatureDoesNotMatch" in text:
        return ("ServerAlly's own AWS credentials were rejected, so this is our side to fix, "
                "not yours.")
    if "MalformedPolicyDocument" in text or "Invalid" in text and "arn" in text.lower():
        return "That does not look like a role ARN. It should read arn:aws:iam::<account>:role/<name>."
    if "DurationSeconds" in text or "duration" in text.lower():
        return ("The role's maximum session duration is shorter than the hour we ask for. "
                "Raise it on the role, or tell us and we will ask for less.")
    return f"Could not assume that role: {text}"
